apiVersion: v1
kind: Namespace
metadata:
  name: intelligent-thinking
  labels:
    name: intelligent-thinking
---
# ConfigMap for shared configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: intelligent-thinking
data:
  DATABASE_URL: "postgresql://postgres:password@postgres:5432/intelligent_thinking"
  REDIS_URL: "redis://redis:6379"
  NEO4J_URL: "bolt://neo4j:7687"
  ELASTICSEARCH_URL: "http://elasticsearch:9200"
  KAFKA_URL: "kafka:9092"
  CONSUL_URL: "consul:8500"
  PROMETHEUS_URL: "prometheus:9090"
  GRAFANA_URL: "grafana:3000"
  JAEGER_URL: "jaeger:14268"
---
# Secret for sensitive data
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: intelligent-thinking
type: Opaque
data:
  # Base64 encoded secrets
  OPENAI_API_KEY: ""
  ANTHROPIC_API_KEY: ""
  GOOGLE_AI_API_KEY: ""
  JWT_SECRET: ""
  ENCRYPTION_KEY: ""
---
# Frontend Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: intelligent-thinking
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: ghcr.io/your-repo/intelligent-thinking/frontend:latest
        ports:
        - containerPort: 3000
        env:
        - name: REACT_APP_API_URL
          value: "http://api-gateway:8080"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
# Backend Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: intelligent-thinking
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: ghcr.io/your-repo/intelligent-thinking/backend:latest
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: app-config
        - secretRef:
            name: app-secrets
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
---
# API Gateway Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-deployment
  namespace: intelligent-thinking
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - name: api-gateway
        image: ghcr.io/your-repo/intelligent-thinking/microservice-api-gateway:latest
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: app-config
        - secretRef:
            name: app-secrets
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
# Auth Service Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service-deployment
  namespace: intelligent-thinking
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-service
        image: ghcr.io/your-repo/intelligent-thinking/microservice-auth-service:latest
        ports:
        - containerPort: 8081
        envFrom:
        - configMapRef:
            name: app-config
        - secretRef:
            name: app-secrets
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
# Thinking Analysis Service Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: thinking-analysis-deployment
  namespace: intelligent-thinking
spec:
  replicas: 2
  selector:
    matchLabels:
      app: thinking-analysis
  template:
    metadata:
      labels:
        app: thinking-analysis
    spec:
      containers:
      - name: thinking-analysis
        image: ghcr.io/your-repo/intelligent-thinking/microservice-thinking-analysis:latest
        ports:
        - containerPort: 8082
        envFrom:
        - configMapRef:
            name: app-config
        - secretRef:
            name: app-secrets
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
---
# Collaboration Service Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: collaboration-deployment
  namespace: intelligent-thinking
spec:
  replicas: 2
  selector:
    matchLabels:
      app: collaboration
  template:
    metadata:
      labels:
        app: collaboration
    spec:
      containers:
      - name: collaboration
        image: ghcr.io/your-repo/intelligent-thinking/microservice-collaboration:latest
        ports:
        - containerPort: 8083
        envFrom:
        - configMapRef:
            name: app-config
        - secretRef:
            name: app-secrets
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
# Blockchain Service Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blockchain-deployment
  namespace: intelligent-thinking
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blockchain
  template:
    metadata:
      labels:
        app: blockchain
    spec:
      containers:
      - name: blockchain
        image: ghcr.io/your-repo/intelligent-thinking/microservice-blockchain:latest
        ports:
        - containerPort: 8084
        envFrom:
        - configMapRef:
            name: app-config
        - secretRef:
            name: app-secrets
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
---
# GraphQL Service Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: graphql-deployment
  namespace: intelligent-thinking
spec:
  replicas: 2
  selector:
    matchLabels:
      app: graphql
  template:
    metadata:
      labels:
        app: graphql
    spec:
      containers:
      - name: graphql
        image: ghcr.io/your-repo/intelligent-thinking/microservice-graphql:latest
        ports:
        - containerPort: 8085
        envFrom:
        - configMapRef:
            name: app-config
        - secretRef:
            name: app-secrets
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
# Advanced AI Service Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: advanced-ai-deployment
  namespace: intelligent-thinking
spec:
  replicas: 2
  selector:
    matchLabels:
      app: advanced-ai
  template:
    metadata:
      labels:
        app: advanced-ai
    spec:
      containers:
      - name: advanced-ai
        image: ghcr.io/your-repo/intelligent-thinking/microservice-advanced-ai:latest
        ports:
        - containerPort: 8086
        envFrom:
        - configMapRef:
            name: app-config
        - secretRef:
            name: app-secrets
        resources:
          requests:
            memory: "1Gi"
            cpu: "1000m"
          limits:
            memory: "2Gi"
            cpu: "2000m"
---
# Search Service Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-deployment
  namespace: intelligent-thinking
spec:
  replicas: 2
  selector:
    matchLabels:
      app: search
  template:
    metadata:
      labels:
        app: search
    spec:
      containers:
      - name: search
        image: ghcr.io/your-repo/intelligent-thinking/microservice-search:latest
        ports:
        - containerPort: 8087
        envFrom:
        - configMapRef:
            name: app-config
        - secretRef:
            name: app-secrets
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
---
# Federated Learning Service Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: federated-learning-deployment
  namespace: intelligent-thinking
spec:
  replicas: 1
  selector:
    matchLabels:
      app: federated-learning
  template:
    metadata:
      labels:
        app: federated-learning
    spec:
      containers:
      - name: federated-learning
        image: ghcr.io/your-repo/intelligent-thinking/microservice-federated-learning:latest
        ports:
        - containerPort: 8088
        envFrom:
        - configMapRef:
            name: app-config
        - secretRef:
            name: app-secrets
        resources:
          requests:
            memory: "1Gi"
            cpu: "1000m"
          limits:
            memory: "2Gi"
            cpu: "2000m"
---
# Quantum Computing Service Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quantum-computing-deployment
  namespace: intelligent-thinking
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quantum-computing
  template:
    metadata:
      labels:
        app: quantum-computing
    spec:
      containers:
      - name: quantum-computing
        image: ghcr.io/your-repo/intelligent-thinking/microservice-quantum-computing:latest
        ports:
        - containerPort: 8089
        envFrom:
        - configMapRef:
            name: app-config
        - secretRef:
            name: app-secrets
        resources:
          requests:
            memory: "1Gi"
            cpu: "1000m"
          limits:
            memory: "2Gi"
            cpu: "2000m"
---
# Networking Service Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: networking-deployment
  namespace: intelligent-thinking
spec:
  replicas: 2
  selector:
    matchLabels:
      app: networking
  template:
    metadata:
      labels:
        app: networking
    spec:
      containers:
      - name: networking
        image: ghcr.io/your-repo/intelligent-thinking/microservice-networking:latest
        ports:
        - containerPort: 8090
        envFrom:
        - configMapRef:
            name: app-config
        - secretRef:
            name: app-secrets
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
# Mobile Service Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mobile-deployment
  namespace: intelligent-thinking
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mobile
  template:
    metadata:
      labels:
        app: mobile
    spec:
      containers:
      - name: mobile
        image: ghcr.io/your-repo/intelligent-thinking/mobile:latest
        ports:
        - containerPort: 3001
        envFrom:
        - configMapRef:
            name: app-config
        - secretRef:
            name: app-secrets
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
# Metaverse Service Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: metaverse-deployment
  namespace: intelligent-thinking
spec:
  replicas: 2
  selector:
    matchLabels:
      app: metaverse
  template:
    metadata:
      labels:
        app: metaverse
    spec:
      containers:
      - name: metaverse
        image: ghcr.io/your-repo/intelligent-thinking/metaverse:latest
        ports:
        - containerPort: 3002
        envFrom:
        - configMapRef:
            name: app-config
        - secretRef:
            name: app-secrets
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
---
# Services
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: intelligent-thinking
spec:
  selector:
    app: frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service
  namespace: intelligent-thinking
spec:
  selector:
    app: api-gateway
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: LoadBalancer
---
# Ingress for external access
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: intelligent-thinking-ingress
  namespace: intelligent-thinking
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
  - hosts:
    - intelligent-thinking.example.com
    secretName: intelligent-thinking-tls
  rules:
  - host: intelligent-thinking.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-service
            port:
              number: 80
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: api-gateway-service
            port:
              number: 8080
---
# HorizontalPodAutoscaler for auto-scaling
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: frontend-hpa
  namespace: intelligent-thinking
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: frontend-deployment
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: api-gateway-hpa
  namespace: intelligent-thinking
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-gateway-deployment
  minReplicas: 3
  maxReplicas: 15
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80 